"""The Windows version resource for the built .exe files, so Explorer's Details tab (and the tooltip, and the
UAC prompt) show which version of Lockdown a file is. Written at build time from src/version.py."""
import os
import sys

TEMPLATE = """# Generated by installer/version_res.py - do not edit.
VSVersionInfo(
  ffi=FixedFileInfo(filevers=%(numbers)s, prodvers=%(numbers)s, mask=0x3f, flags=0x0, OS=0x40004,
                    fileType=0x1, subtype=0x0, date=(0, 0)),
  kids=[
    StringFileInfo([StringTable('040904B0', [
      StringStruct('CompanyName', 'Lockdown'),
      StringStruct('FileDescription', %(description)r),
      StringStruct('FileVersion', %(version)r),
      StringStruct('InternalName', %(name)r),
      StringStruct('LegalCopyright', ''),
      StringStruct('OriginalFilename', %(filename)r),
      StringStruct('ProductName', 'Lockdown'),
      StringStruct('ProductVersion', %(version)r)])]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])]
)
"""


def numbers(version: str) -> tuple:
    """"0.64.0" -> (0, 64, 0, 0) - Windows wants four numbers."""
    parts = [int(p) for p in version.split(".")[:4] if p.isdigit()]
    return tuple((parts + [0, 0, 0, 0])[:4])


def write(path: str, version: str, name: str, description: str) -> str:
    with open(path, "w", encoding="utf-8") as f:
        f.write(TEMPLATE % {"numbers": numbers(version), "version": version, "name": name,
                            "filename": f"{name}.exe", "description": description})
    return path


if __name__ == "__main__":   # build.ps1: version_res.py <out dir>
    sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "src"))
    from version import VERSION
    out = sys.argv[1]
    for name, description in (("Lockdown", "Lockdown"), ("LockdownService", "Lockdown enforcement service"),
                              ("LockdownSetup", "Lockdown setup")):
        print(write(os.path.join(out, f"version_{name}.txt"), VERSION, name, description))
